import Head from "next/head";
import { useState } from "react";
import ArchetypeProfile from "../src/components/ArchetypeProfile/ArchetypeProfile";
import Questionnaire from "../src/components/Questionnaire/Questionnaire";
import { getArchetype } from "../src/helpers/archetype";
import { Archetype, onActionEvents, onActionType } from "../src/types";
import achetypes from "../src/data/archetypes.json";
import IconButton from "../src/components/IconButton/IconButton";
import Popup from "../src/components/Popup/Popup";
import ResultsPageBanner from "../src/components/ResultsPageBanner/ResultsPageBanner";
import { Stack } from "@mui/material";

type CurrentPhase = "pre" | "questionnaire" | "results";

export default function Home() {
  const [archetype, setArchetype] = useState<Archetype>(achetypes[0]);
  const [currPhase, setCurrPhase] = useState<CurrentPhase>("questionnaire");

  const onAction: onActionType = ({ type, data }) => {
    switch (type) {
      case onActionEvents.getAnswers:
        const archetype = getArchetype(data);
        if (archetype) setArchetype(archetype);
        setCurrPhase("results");
        break;
      case onActionEvents.takeQuiz:
        setCurrPhase("questionnaire");
        break;

      default:
        break;
    }
  };

  return (
    <div>
      <Head>
        <title>Power Ranger Team</title>
        <meta name="description" content="Generated by the power rangers" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {currPhase === "pre" ? (
          <Stack direction="column" spacing={10} alignItems="center">
            <Popup onAction={onAction} />
            <ResultsPageBanner onAction={onAction} />
            <IconButton onAction={onAction} />
          </Stack>
        ) : currPhase === "questionnaire" ? (
          <Questionnaire onAction={onAction} />
        ) : currPhase === "results" ? (
          <ArchetypeProfile onAction={onAction} archetype={archetype} />
        ) : (
          <></>
        )}
      </main>

      <footer></footer>
    </div>
  );
}
