import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Power Ranger Team</title>
        <meta name="description" content="Generated by the power rangers" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </div>
  );
}
