import Head from "next/head";
import Popup from "../styles/src/components/Popup/Popup";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Power Ranger Team</title>
        <meta name="description" content="Generated by the power rangers" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Popup onAction={() => {}} />
      </main>

      <footer></footer>
    </div>
  );
}
